name: CI

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "16.x"
          check-latest: yes
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Package
        run: zip -r bundle.zip ./
      - name: Setup Terraform environment
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform -chdir=infrastructure init
      - name: Terraform Apply
        run: terraform -chdir=infrastructure apply -auto-approve
